method: 'clipdraw'

image_size: 224 # canvas size
path_svg: ~ # if you want to load a svg file and train from it

# train
num_iter: 1000
num_stages: 1 # training stages, you can train x strokes, then freeze them and train another x strokes etc
lr_schedule: True
lr: 1
width_lr: 0.1
color_lr: 0.01

# SVG path attr
num_paths: 512 # number of strokes
max_width: 50 # stroke width
black_stroke_color: False

# loss
num_aug: 4