method: 'styleclipdraw'

image_size: 224 # canvas size
path_svg: ~ # if you want to load an svg file and train from it

# train
num_iter: 1000
num_stages: 1 # training stages, you can train x strokes, then freeze them and train another x strokes etc
lr_schedule: True # anneal learning rate
lr: 1
width_lr: 0.1
color_lr: 0.01

# strokes
num_paths: 512 # number of strokes
max_width: 50 # stroke width
black_stroke_color: False
style_strength: 50  # How strong the style should be. 100 (max) is a lot. 0 (min) is no style.

# loss
num_aug: 10 # Number of image augmentations