[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PyTorch-SVGRender"
authors = [{name = "Ximing Xing", email = "ximingxing@gmail.com"}]
dynamic = ["version", "description"]
