#-----------------#
#  Global Config  #
#-----------------#

# optional args
target: ~ # target file
prompt: ~ # textual prompt
neg_prompt: "nsfw, lowres, (bad), text, error, fewer, extra, missing, worst quality, jpeg artifacts, low quality, watermark, unfinished, displeasing, oldest, early, chromatic aberration, signature, extra digits, artistic error, username, scan" # negative prompt
result_path: './workspace' # results output path

# Accelerate config
state:
  cpu: False   # use CPU (false means use GPU)
  mprec: 'no'  # mixed precision, choices: 'no', 'fp16', 'bf16'
#  wandb: False
#  tensorboard: False

# Diffusers config
diffuser:
  download: False        # set to true the first time it runs
  force_download: False
  resume_download: False
# PyDiffVG config
diffvg:
  print_timing: False

# Reproduction
seed: 951222
# Batch Processing
multirun: False  # whether to run multiple times
srange: ~        # seed range, example: [100, 100]

# Logging
save_step: 10    # save interval
eval_step: 10    # evaluation interval

# Visualization Configuration
mv: False       # whether to generate video
framefreq: 5    # image saving interval
framerate: 24   # video frame rate

# Hydra Configuration
hydra:
  help:
    app_name: 'SVGRender'
  run:
    # output directory for normal runs
    # warning: make sure that the L56-58 of '/libs/engine/model_state.py' and 'dir' are modified together
    dir: ./${result_path}/${x.method}-${now:%Y-%m-%d-%H-%M}

# Default Settings
defaults:
  - _self_
  - x: ~
  - override hydra/job_logging: disabled # outputs only to stdout (no log file)